### ISSUE TITLE
Hi PVPBET! Could I work with you?

### ISSUE THREAD

**Issue by forestDev1212** [pvpbet/pvpbet#1]
Hi, I am senior full stack engineer who is very familiar with igaming development industry.

If you don't mind could I work with you?

I have attached some files so that you can understand my recent works.

My Discord Username: gohchenkai
![mint360](https://github.com/user-attachments/assets/63b26eca-bd92-4606-a5de-8bbb0eacac59)
![ru-betting-pc](https://github.com/user-attachments/assets/1a4e6c37-a9f7-452a-bae6-dc131ae7676c)
![1](https://github.com/user-attachments/assets/c9c1dec4-b71b-4c27-82ab-db4b99bfa5df)
![Screenshot_7](https://github.com/user-attachments/assets/39acf46c-5530-4294-bed9-b7b4abfe8a79)
![Screenshot_8](https://github.com/user-attachments/assets/d2d9ba9e-4eea-4cb5-9762-1e183d81d413)

**Comment by pvpbet** [comment]
Thank you for your interest. We’ll reach out if we have any future needs.
